name: 'Deploy WordPress'
description: 'Deploy WordPress code to a server'
author: 'rtCamp'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/devs-in-the-cloud/action-deploy-wordpress:v2.3.1'
branding:
  icon: 'upload-cloud'
  color: 'yellow'
